inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - "pkg/**/*"
    - "coverage/**/*"
    - "exe/**/*"

  DisplayCopNames: true
  TargetRubyVersion: 3.0.0

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

HashSyntax:
  EnforcedStyle: ruby19

Style/AsciiComments:
  Enabled: true

# Allow class without document
Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: true

# String will be frozen by default since ruby 3.0.0.
Style/FrozenStringLiteralComment:
  Enabled: false

# skip self receiver
Style/RedundantSelf:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20
